# Site settings
title: Prisma Web Tech
header-img: img/photo-prisma.jpg
email: contact@prismamedia.com
copyright_name: Prisma Media
description: "Blog des développeurs web du Groupe Prisma Media."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: PrismaMedia
github_username: 
facebook_username: PrismaLabs
email_username: 

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

author:
    name: Prisma Media Tech
    # email: contact@prismamedia.com
    uri: http://www.pmdrecrute.com/